name: hagg

dependencies:
  - base >=4.14 && <4.15

ghc-options:
  - -Wall

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - hagg

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hagg
      - hspec

default-extensions:
  - ConstraintKinds
  - ImportQualifiedPost
  - OverloadedStrings
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
